#!/bin/bash

declare current_title
declare current_path
declare current_description
declare current_detail
declare -A current_options

declare -a ca_titles
declare -A ca_paths
declare -A ca_descriptions
declare -A ca_details
declare -A ca_optionses

function push_current() {
  ca_titles+=("$current_title")
  ca_paths["$current_title"]="$current_path"
  ca_descriptions["$current_title"]="$current_description"
  ca_details["$current_title"]="$current_detail"
  ca_optionses["$current_title"]="$(declare -p current_options)"

  current_title=""
  current_options=()
}

function title() {
  if [ -n "$current_title" ]; then
    push_current
  fi
  current_title="$*"
}

function path() {
  current_path="$*"
}

function description() {
  current_description="$*"
}

function detail() {
  current_detail="$*"
}

function options() {
  current_options["$1"]="$2"
}

on_off() {
  if [ $# -lt 2 ]; then
    echo 'off'
  elif [ "$1" -eq "$2" ]; then
    echo 'on'
  else
    echo 'off'
  fi
}

submenu() {
  local title="$1"
  local path="${ca_paths[$title]}"
  local detail="${ca_details[$title]}"
  eval "${ca_optionses[$title]}"

  current_value=$(cat "$path")

  declare -a dialog_params=()
  dialog_params+=(--title "$title")
  dialog_params+=(--radiolist "$detail")
  dialog_params+=(0 60 0)
  for key in "${!current_options[@]}"; do
    dialog_params+=("$key" "${current_options[$key]}" "$(on_off 50 \
                    "$current_value")")
  done
  choice=$(dialog "${dialog_params[@]}" 2>&1 >/dev/tty)
  if [ $? -eq 0 ]; then
    echo "$choice" >"$path" || exit 1
  fi
}



mainmenu() {
  declare -a dialog_params=()
  dialog_params+=(--title 'VAIO Care')
  dialog_params+=(--menu "Select an item to configure")
  dialog_params+=(0 60 0)
  for title in "${ca_titles[@]}"; do
    if [ -f "${ca_paths[$title]}" ]; then
      dialog_params+=("$title" "${ca_descriptions[$title]}")
    fi
  done
      
  while true; do
    choice=$(dialog "${dialog_params[@]}" 2>&1 >/dev/tty)
    [ $? -ne 0 ] && return

    submenu "$choice"
  done
}

# Load Options from Database
source './database'
push_current

mainmenu
